version: '2'
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://nycdb:nycdb@db/nycdb
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=nycdb
      - POSTGRES_DB=nycdb
      - POSTGRES_PASSWORD=nycdb
    ports:
      - 5432:5432
